const BUILD='28.0.0';
const CACHE='stack-v28-minimal-architecture';
const SCRIPT_PATHS=["backup.js","stack-data.js","stack-finance.js","stack-fx.js","v22.js","v22.1.js","v22.2.js","v22.3-income.js","v22.12-ui-rebuild.js","v22.13-fx-history-safe.js","v22.14-fx-overview.js","v22.15-currency-dashboard.js","v22.16-fx-stability.js","v22.18-fx-actual.js","v22.20-finance-stable.js","stack-persistence.js","stack-v23-shell.js","stack-v23-deals.js","stack-v23-fitness.js","stack-v23-calendar-visual.js","stack-v23-fitness-pack.js","stack-v23-fitness-day-picker.js","stack-v23-fitness-month-label.js","stack-v23-fitness-info.js","stack-v23-fitness-progress.js","stack-v23-fitness-goals.js","stack-v23-fitness-engine.js","stack-v23-fitness-library.js","stack-v23-fitness-intelligence.js","stack-v24-fitness-analytics.js","stack-v24-mobile-readability.js","stack-v23-stability.js","stack-v24-unified.js","stack-v25-finance.js","stack-v26-deals-intelligence.js","stack-v27-bootstrap.js","stack-v27-core.js","stack-v27-1-fitness-tabs.js","stack-v27-3-nutrition.js","stack-v27-3-1-nutrition-overflow.js","stack-v27-4-nutrition-goals.js","stack-v27-5-quick-foods.js","stack-v27-5-1-nutrition-simplify.js","stack-v27-5-2-nutrition-minimal.js","stack-v27-5-3-ration.js","stack-v27-5-5-nutrition-reorder.js","stack-v28-minimal.js"];
const FITNESS_VISUALS=['lower-knee-v2321.webp','posterior-chain-v2321.webp','upper-push-v2321.webp','upper-pull-v2321.webp','core-accessory-v2321.webp'];
const STATIC=['./','./index.html','./manifest.webmanifest','./icon.svg',...SCRIPT_PATHS.map(x=>`./${x}?build=${BUILD}`),...FITNESS_VISUALS.map(x=>`./assets/fitness/${x}?build=${BUILD}`)];
self.addEventListener('install',event=>{self.skipWaiting();event.waitUntil((async()=>{const cache=await caches.open(CACHE);for(const path of STATIC){try{await cache.add(new Request(path,{cache:'reload'}))}catch(error){console.warn('STACK precache skipped',path,error)}}})())});
self.addEventListener('activate',event=>{event.waitUntil((async()=>{const keys=await caches.keys();await Promise.all(keys.filter(key=>key.startsWith('stack-v')&&key!==CACHE).map(key=>caches.delete(key)));if(self.registration.navigationPreload)try{await self.registration.navigationPreload.enable()}catch(_error){}await self.clients.claim();const clients=await self.clients.matchAll({type:'window',includeUncontrolled:true});await Promise.all(clients.map(client=>client.navigate(client.url).catch(()=>null)))})())});
async function cacheShell(response){if(!response||!response.ok)return;try{const cache=await caches.open(CACHE);await Promise.all([cache.put('./index.html',response.clone()),cache.put('./',response.clone())])}catch(_error){}}
async function navigationResponse(event){try{const preload=await event.preloadResponse;if(preload&&preload.ok){await cacheShell(preload);return preload}const network=await fetch(event.request,{cache:'no-store'});if(network&&network.ok)await cacheShell(network);return network}catch(_error){const cache=await caches.open(CACHE);return await cache.match('./index.html')||await cache.match('./')||await caches.match('./index.html')}}
async function networkFirst(request){try{const response=await fetch(request,{cache:'no-store'});if(response&&response.ok){try{const cache=await caches.open(CACHE);await cache.put(request,response.clone())}catch(_error){}}return response}catch(_error){return await caches.match(request,{ignoreSearch:true})}}
self.addEventListener('fetch',event=>{if(event.request.method!=='GET')return;const request=event.request,navigation=request.mode==='navigate'||request.destination==='document';if(navigation){event.respondWith(navigationResponse(event));return}event.respondWith(networkFirst(request))});