/* STACK v22 — Smart Finance & Control */
(()=>{'use strict';
const BUILD='v22-smart-finance-2026-09-04';
function init(){
 if(typeof state==='undefined'||!state.savings)return;
 state.savings.goals.forEach((g,i)=>{g.status=g.status||'active';g.startDate=g.startDate||g.createdAt||'';g.tx=g.tx||[];g.tx.forEach((t,j)=>{if(!t.id)t.id='t'+Date.now()+i+'_'+j})});
 try{save()}catch(e){}
 installStartDate();patchGoalEditor();patchTransactions();patchDetail();patchHistory();patchChart();
 try{renderSavings()}catch(e){}
 console.info('STACK',BUILD)
}
function installStartDate(){const start=document.getElementById('sgStart');if(!start||document.getElementById('sgStartDate'))return;const row=document.createElement('div');row.className='form-row';row.innerHTML='<label>Баланс на дату</label><input id="sgStartDate" type="date">';start.closest('.form-row').after(row)}
function money2(v,c){return new Intl.NumberFormat('ru-RU',{maximumFractionDigits:2}).format(v||0)+' '+SAV_SYMBOL[c]}
function actualRate(g){const a=(g.tx||[]).filter(t=>+t.amount>0&&t.date);if(!a.length)return 0;const first=new Date(a.map(t=>t.date).sort()[0]+'T12:00:00'),now=new Date(),m=Math.max(1,(now.getFullYear()-first.getFullYear())*12+now.getMonth()-first.getMonth()+1);return a.reduce((s,t)=>s+(+t.amount||0),0)/m}
function forecast(left,rate){if(!(left>0)||!(rate>0))return '—';const d=new Date();d.setMonth(d.getMonth()+Math.ceil(left/rate));return d.toLocaleDateString('ru-RU',{month:'long',year:'numeric'})}
function planState(g,b){if(!g.startDate||!(+g.monthly>0))return {c:'#58a6ff',t:'План не рассчитан'};const d=new Date(g.startDate+'T12:00:00'),n=new Date(),m=Math.max(0,(n.getFullYear()-d.getFullYear())*12+n.getMonth()-d.getMonth()),plan=(+g.start||0)+(+g.monthly||0)*m,diff=b-plan,tol=Math.max((+g.monthly||0)*.15,1);return diff>tol?{c:'#68d43f',t:'Опережение '+money2(diff,g.currency)}:diff<-tol?{c:'#f04b6c',t:'Отставание '+money2(Math.abs(diff),g.currency)}:{c:'#58a6ff',t:'По плану'}}
function patchGoalEditor(){const old=openSavingsGoal;openSavingsGoal=function(id=null){old(id);const g=id?state.savings.goals.find(x=>x.id===id):null;const el=document.getElementById('sgStartDate');if(el)el.value=g?.startDate||''};const oldSave=saveSavingsGoal;saveSavingsGoal=function(){oldSave();const g=savEditingId?state.savings.goals.find(x=>x.id===savEditingId):state.savings.goals.find(x=>x.id===state.savings.selectedId);if(g){g.startDate=document.getElementById('sgStartDate')?.value||g.startDate||'';g.status=g.status||'active';g.createdAt=g.createdAt||new Date().toISOString().slice(0,10);save();renderSavings()}};sgSave.onclick=saveSavingsGoal}
let editTx=null;
function patchTransactions(){const oldOpen=openSavingsTx;openSavingsTx=function(t){editTx=null;oldOpen(t)};const oldSave=saveSavingsTx;saveSavingsTx=function(){const g=selectedSavingsGoal();if(editTx&&g){const t=g.tx.find(x=>x.id===editTx),amt=Math.max(0,+stAmount.value||0);if(!t||amt<=0||!stDate.value)return;if(savTxType<0&&amt>goalBalance(g)-t.amount)return setSavError('stError','Нельзя снять больше, чем сейчас накоплено.');Object.assign(t,{amount:amt*savTxType,date:stDate.value,note:stNote.value.trim()});save();savTxModal.classList.remove('active');editTx=null;renderSavings();return}oldSave();const last=g?.tx?.at(-1);if(last&&!last.id){last.id='t'+Date.now()+Math.random().toString(36).slice(2,6);save()}};stSave.onclick=saveSavingsTx;window.stackEditTx=id=>{const g=selectedSavingsGoal(),t=g?.tx?.find(x=>x.id===id);if(!t)return;editTx=id;savTxType=t.amount>=0?1:-1;savTxTitle.textContent='РЕДАКТИРОВАНИЕ ОПЕРАЦИИ';stAmount.value=Math.abs(t.amount);stDate.value=t.date||'';stNote.value=t.note||'';savTxModal.classList.add('active')}}
function patchDetail(){renderSavingsDetail=function(g){const r=document.getElementById('savDetail');if(!g){r.innerHTML='<div class="sav-empty" style="grid-column:1/-1">Создайте первую цель накопления</div>';return}const b=goalBalance(g),p=g.target?Math.min(1,b/g.target):0,left=Math.max(0,g.target-b),rate=actualRate(g),ps=planState(g,b);r.innerHTML=`<div class="ring sav-ring" style="--v:${p*100};--c1:#0877f3;--c2:${g.color}"><span>${pct(p)}%</span></div><div class="sav-detail-lines"><div class="sav-line"><span>Цель</span><strong>${esc(g.name)}</strong></div><div class="sav-line"><span>Накоплено</span><strong>${money2(b,g.currency)}</strong></div><div class="sav-line"><span>Осталось</span><strong>${money2(left,g.currency)}</strong></div><div class="sav-line"><span>План / месяц</span><strong>${money2(g.monthly,g.currency)}</strong></div><div class="sav-line"><span>Фактический темп</span><strong>${money2(rate,g.currency)}/мес</strong></div><div class="sav-line"><span>Прогноз по плану</span><strong>${forecast(left,+g.monthly||0)}</strong></div><div class="sav-line"><span>Прогноз по факту</span><strong>${forecast(left,rate)}</strong></div><div style="color:${ps.c};border:1px solid ${ps.c};border-radius:99px;padding:4px 8px;font-size:8px;font-weight:800;display:inline-block;margin:5px 0">${ps.t}</div><div style="font-size:8px;color:#7f899c">Старт: ${money2(g.start,g.currency)}${g.startDate?' на '+new Date(g.startDate+'T12:00:00').toLocaleDateString('ru-RU'):''}</div><div style="display:flex;gap:5px;flex-wrap:wrap;margin-top:7px"><button class="btn" data-editg>Редактировать</button><button class="btn" data-complete>${g.status==='completed'?'Вернуть в активные':'✓ Завершить'}</button><button class="btn" data-archive>${g.status==='archived'?'Вернуть':'В архив'}</button></div></div>`;r.querySelector('[data-editg]').onclick=()=>openSavingsGoal(g.id);r.querySelector('[data-complete]').onclick=()=>{g.status=g.status==='completed'?'active':'completed';g.completedAt=g.status==='completed'?new Date().toISOString().slice(0,10):'';save();renderSavings()};r.querySelector('[data-archive]').onclick=()=>{g.status=g.status==='archived'?'active':'archived';save();renderSavings()}}}
function patchHistory(){renderSavingsHistory=function(g){const r=document.getElementById('savHistory');if(!g){r.innerHTML='<div class="sav-empty">Нет операций</div>';return}const a=[...(g.tx||[])].sort((x,y)=>(y.date||'').localeCompare(x.date||''));r.innerHTML=a.length?a.map(t=>`<div class="sav-history-row" style="grid-template-columns:72px 1fr auto auto"><span>${t.date||'—'}</span><span>${esc(t.note||'Без комментария')}</span><strong class="${t.amount>=0?'plus':'minus'}">${t.amount>=0?'+':''}${money2(t.amount,g.currency)}</strong><span><button class="btn" data-e="${t.id}">✎</button> <button class="btn" data-d="${t.id}" style="color:#f06a83">×</button></span></div>`).join(''):'<div class="sav-compact-message">Операций пока нет.</div>';r.querySelectorAll('[data-e]').forEach(x=>x.onclick=()=>stackEditTx(x.dataset.e));r.querySelectorAll('[data-d]').forEach(x=>x.onclick=()=>{if(confirm('Удалить эту операцию?')){g.tx=g.tx.filter(t=>t.id!==x.dataset.d);save();renderSavings()}})}}
function patchChart(){const old=renderSavingsChart;renderSavingsChart=function(g){old(g);const s=document.getElementById('savChart');if(!s||!g)return;s.querySelectorAll('circle').forEach((c,i)=>{c.style.cursor='pointer';c.addEventListener('click',()=>{const title=c.querySelector('title');if(title)alert(title.textContent)})})}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(init,0),{once:true});else setTimeout(init,0);
})();