/* STACK v22.2 — Core Stability
   Additive compatibility layer. Keeps KEY and existing state intact. */
(()=>{'use strict';
const BUILD='v22.2-core-stability-2026-09-05';
const SCHEMA=22.2;
let internalSave=false;
const clone=x=>{try{return structuredClone(x)}catch(e){return JSON.parse(JSON.stringify(x))}};
function ensureMeta(s){if(!s||typeof s!=='object')return s;s._meta=(s._meta&&typeof s._meta==='object')?s._meta:{};s._meta.schemaVersion=SCHEMA;s._meta.revision=Math.max(0,Number(s._meta.revision)||0);s._meta.updatedAt=s._meta.updatedAt||new Date().toISOString();return s}
function enrich(s){if(!s||typeof s!=='object')return s;ensureMeta(s);if(s.savings&&Array.isArray(s.savings.goals))s.savings.goals.forEach((g,i)=>{g.status=['active','completed','archived'].includes(g.status)?g.status:'active';g.startDate=String(g.startDate||g.createdAt||'').slice(0,10);g.createdAt=String(g.createdAt||'').slice(0,10);g.completedAt=String(g.completedAt||'').slice(0,10);g.tx=Array.isArray(g.tx)?g.tx:[];g.tx.forEach((t,j)=>{t.id=t.id||('t'+Date.now()+i+'_'+j)})});return s}
function score(s){return Number(s?._meta?.revision)||0}
function time(s){const x=Date.parse(s?._meta?.updatedAt||'');return Number.isFinite(x)?x:0}
function richer(a,b){const count=s=>{let n=0;n+=(s?.processes?.length||0)*10;n+=(s?.journal?.length||0)*4;n+=(s?.savings?.goals?.length||0)*20;(s?.months||[]).forEach(m=>(m||[]).forEach(r=>(r||[]).forEach(v=>{if(v)n++})));(s?.savings?.goals||[]).forEach(g=>n+=(g.tx?.length||0)*3);return n};return count(a)>=count(b)?a:b}
async function reconcile(){try{const localRaw=typeof KEY!=='undefined'?localStorage.getItem(KEY):null,local=localRaw?JSON.parse(localRaw):null,idb=typeof idbLoadState==='function'?await idbLoadState():null;if(!local&&!idb)return;let best;if(local&&idb){best=score(local)!==score(idb)?(score(local)>score(idb)?local:idb):(time(local)!==time(idb)?(time(local)>time(idb)?local:idb):richer(local,idb))}else best=local||idb;if(!best)return;best=enrich(clone(best));const current=richer(state||{},best);if(current===best||score(best)>score(state)||time(best)>time(state)){state=best;try{normalize()}catch(e){}internalSave=true;try{localStorage.setItem(KEY,JSON.stringify(state));if(typeof idbSaveState==='function')idbSaveState(state)}finally{internalSave=false}try{renderAll()}catch(e){}}}catch(e){console.warn('STACK v22.2 reconcile failed',e)}}
function patchMigration(){if(typeof migrateStoredState!=='function'||migrateStoredState.__v222)return;const old=migrateStoredState;const fn=function(x){const before=x&&typeof x==='object'?clone(x):x;const out=old(x);if(before&&out){out._meta=before._meta||out._meta;(before.savings?.goals||[]).forEach((g,i)=>{const q=out.savings?.goals?.[i];if(!q)return;['status','startDate','createdAt','completedAt'].forEach(k=>{if(g[k]!==undefined)q[k]=g[k]});(g.tx||[]).forEach((t,j)=>{if(q.tx?.[j]&&t.id)q.tx[j].id=t.id})})}return enrich(out)};fn.__v222=true;migrateStoredState=fn}
function patchMarks(){try{validMark=v=>v==='✓'||v==='◐'||v==='○'||v==='—'||v==='';cycle=v=>v===''?'✓':v==='✓'?'◐':v==='◐'?'○':v==='○'?'—':'';activeCompletion=arr=>{let pts=0,total=0,done=0;arr.forEach(v=>{if(v==='✓'){pts+=1;total++;done++}else if(v==='◐'){pts+=.5;total++}else if(v==='○')total++});return {rate:total?pts/total:null,done,total}}}catch(e){console.warn('STACK v22.2 marks patch failed',e)}}
function patchSave(){if(typeof save!=='function'||save.__v222)return;const old=save;const fn=function(...a){if(typeof state!=='undefined'&&!internalSave){enrich(state);state._meta.revision=(Number(state._meta.revision)||0)+1;state._meta.updatedAt=new Date().toISOString()}return old.apply(this,a)};fn.__v222=true;save=fn}
function boot(){try{patchMigration();patchMarks();if(typeof state!=='undefined')enrich(state);patchSave();setTimeout(reconcile,250);console.info('STACK',BUILD)}catch(e){console.warn('STACK v22.2 boot failed',e)}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(boot,40),{once:true});else setTimeout(boot,40);
})();